Isen.DotNet.Web/Models/ErrorViewModel.cs
using System;

namespace Isen.DotNet.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Isen.DotNet.Web/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class AddressController : BaseController<Address>
    {
        public AddressController(
            ILogger<AddressController> logger,
            IAddressRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Isen.DotNet.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class CategoryController : BaseController<Category>
    {
        public CategoryController(
            ILogger<CategoryController> logger,
            ICategoryRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Isen.DotNet.Web/Controllers/CommuneController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class CommuneController : BaseController<Commune>
    {
        public CommuneController(
            ILogger<CommuneController> logger,
            ICommuneRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Isen.DotNet.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;

namespace Isen.DotNet.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Isen.DotNet.Web/Controllers/POIController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;

namespace Isen.DotNet.Web.Controllers
{
    public class POIController : BaseController<POI>
    {
        public POIController(
            ILogger<POIController> logger,
            IPOIRepository repository) 
            : base(logger, repository)
        {
        }
    }
}

Isen.DotNet.Web/Controllers/_BaseApiController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;
using Isen.DotNet.Library.Models.Base;
using System.Dynamic;

namespace Isen.DotNet.Web.Controllers
{
    public abstract partial class BaseController<T> : Controller
        where T : BaseModel
    {
        [HttpGet]
        [Route("api/[controller]")]
        public virtual JsonResult GetAll()
        {
            var all = _repository
                .GetAll()
                .Select(t => t.ToDynamic())
                .ToList();
            return Json(all);
        }

        [HttpGet]
        [Route("api/[controller]/{id}")]
        public virtual JsonResult GetById(int id)
        {
            var single = _repository.Single(id);
            return Json(single);
        }

        [HttpPost]
        [Route("api/[controller]")]
        public virtual JsonResult Create([FromBody] T model)
        {
            _repository.Update(model);
            _repository.Save();
            return Json(model.ToDynamic());
        }

        [HttpPut]
        [Route("api/[controller]/{id}")]
        public virtual JsonResult Update(int? id, [FromBody] T model)
        {
            if (id == null || model == null || model.Id != id)
                return Json(null);

            _repository.Update(model);
            _repository.Save();
            return Json(model.ToDynamic());
        }

        [HttpDelete]
        [Route("api/[controller]/{id}")]
        public virtual IActionResult Remove(int? id)
        {
            if (id == null)
                return BadRequest();
            if (_repository.Single(id.Value) == null)
                return NotFound();
            _repository.Delete(id.Value);
            _repository.Save();
            return new NoContentResult();
        }
    }
}

Isen.DotNet.Web/Controllers/_BaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Isen.DotNet.Web.Models;
using Isen.DotNet.Library.Repositories.Interfaces;
using Isen.DotNet.Library.Repositories.InMemory;
using Isen.DotNet.Library.Models.Implementation;
using Microsoft.Extensions.Logging;
using Isen.DotNet.Library.Models.Base;

namespace Isen.DotNet.Web.Controllers
{
    public abstract partial class BaseController<T> : Controller
        where T : BaseModel
    {
        protected IBaseRepository<T> _repository;
        protected readonly ILogger<BaseController<T>> _logger;

        public BaseController(
            ILogger<BaseController<T>> logger,
            IBaseRepository<T> repository)
        {
            _repository = repository;
            _logger = logger;
        }

        public virtual IActionResult Index()
        {            
            var model = _repository.GetAll();
            return View(model);
        }

        public virtual IActionResult Detail(int? id)
        {
            // Pas d'id > form vide (création)
            if (id == null) return View();
            // Récupérer la ville et la passer à la vue
            var model = _repository.Single(id.Value);
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult Detail(T model)
        {
            _repository.Update(model);
            _repository.Save();
            return RedirectToAction("Index");
        }

        public virtual IActionResult Delete(int? id)
        {
            if (id != null)
            {
                _repository.Delete(id.Value);
                _repository.Save();
            }
            return RedirectToAction("Index");
        }
    }
}

Isen.DotNet.Web/Views/Address/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@using Isen.DotNet.Library.Repositories.Interfaces;
@{
    ViewData["Title"] = "Address (détail)";
}
@inject ICommuneRepository _communeRepository;
@model Address

<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/commune/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Text" class="control-label">Texte :</label>
                <input type="text" class="form-control"
                    id="Text" placeholder="Texte"
                    value="@Model?.Text" asp-for="Text" />
            </div>
            <div>
                <label for="Code" class="control-label">Code Postal : </label>
                <input type="number" class="form-control"
                    id="Code" placeholder="Code"
                    value="@Model?.Code" asp-for="Code" />
            </div>
            <div>
                <label for="CommuneId">
                    Commune
                </label>
                @Html.DropDownListFor(
                    p => p.Commune,
        
                    new SelectList(
                        _communeRepository.GetAll(), 
                        "Id", 
                        "Name"),
                    "<Sélectionnez une Commune>",
                    new { @class = "form-control" })
            </div>
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Address" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Web/Views/Address/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Addresses";
}
@model IEnumerable<Address>

<div class="row">
    <div class="col-md-12">
        <h1>Adresses : <small>/address/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Address" asp-action="Detail">Ajouter une adresse...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Texte</th>
                <th>Code Postal</th>
                <th>Commune</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var address in Model)
            {
            <tr>
                <td>@address.Id</td>
                <td>@address.Text</td>
                <td>@address.Code</td>
                <td>@address.Commune?.Name</td>
                <td>
                    <a class="btn btn-default" asp-controller="Address" asp-action="Detail" asp-route-id="@address.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="Address" asp-action="Delete" asp-route-id="@address.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Web/Views/City/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "City (détail)";
}
@model City

<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/city/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Name" class="control-label">Nom de la ville :</label>
                <input type="text" class="form-control"
                    id="Name" placeholder="Nom de la ville"
                    value="@Model?.Name" asp-for="Name" />
            </div>
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="City" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Web/Views/City/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Villes";
}
@model IEnumerable<City>

<div class="row">
    <div class="col-md-12">
        <h1>Villes <small>/city/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="City" asp-action="Detail">Ajouter une ville...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Population</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var city in Model)
            {
            <tr>
                <td>@city.Id</td>
                <td>@city.Name</td>
                <td>@city.PersonCount</td>
                <td>
                    <a class="btn btn-default" asp-controller="City" asp-action="Detail" asp-route-id="@city.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="City" asp-action="Delete" asp-route-id="@city.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Web/Views/Commune/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Commune (détail)";
}
@model Commune

<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/commune/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form-horizontal" asp-action="Detail">
            <input type="hidden" value="@Model?.Id" asp-for="Id" />
            <div>
                <label for="Name" class="control-label">Nom de la commune :</label>
                <input type="text" class="form-control"
                    id="Name" placeholder="Nom de la commune"
                    value="@Model?.Name" asp-for="Name" />
            </div>
            <br />
            <input type="submit" class="btn btn-primary" value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Commune" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Web/Views/Commune/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Commune";
}
@model IEnumerable<Commune>

<div class="row">
    <div class="col-md-12">
        <h1>Communes : <small>/commune/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Commune" asp-action="Detail">Ajouter une commune...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var commune in Model)
            {
            <tr>
                <td>@commune.Id</td>
                <td>@commune.Name</td>
                <td>
                    <a class="btn btn-default" asp-controller="Commune" asp-action="Detail" asp-route-id="@commune.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" asp-controller="Commune" asp-action="Delete" asp-route-id="@commune.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Web/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "_LayoutEmpty";
}
<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/home/about</small></h1>
        <p>Ceci est le contenu de la vue Home, action About</p>
    </div>
</div>

Isen.DotNet.Web/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/home/contact</small></h1>
        <p>Ceci est le contenu de la vue Home, action Contact</p>
    </div>
</div>

Isen.DotNet.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
    ViewData["Desc"] = "Description longue du site";
    var urls = new List<string>
    {
        "http://localhost:5000/Home/Index",
        "http://localhost:5000/Home/About",
        "http://localhost:5000/Home/Contact"
    };
}
<div class="row">
    <div class="col-md-12">
        <h1>Home <small>/home/index</small></h1>
        <p>Ceci est le contenu de la vue Home, action Index</p>
    </div>
</div>
<div class="row">
    <div class="col-md-6 bg-info">1</div>
    <div class="col-md-6 bg-info">2</div>
</div>
<div class="row">
    @foreach(var url in urls)
    {
        <div class="col-md-4 bg-info">
            <a href="@url">@url</a>
        </div>
    }
</div>

Isen.DotNet.Web/Views/Person/Detail.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@using Isen.DotNet.Library.Repositories.Interfaces;
@{
    ViewData["Title"] = "Personne (détail)";
}
@inject ICityRepository _cityRepository;
@model Person;

<div class="row">
    <div class="col-md-12">
        <h1>Détail d'une ville <small>/person/detail</small></h1>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <form class="form" asp-action="Detail">

            <input type="hidden" 
                value="@Model?.Id" asp-for="Id" />

            <div>
                <label for="FirstName" class="control-label">
                    Prénom :
                </label>
                <input type="text" class="form-control"
                    id="FirstName" placeholder="Prénom"
                    value="@Model?.FirstName" asp-for="FirstName" />
            </div>

            <div>
                <label for="LastName" class="control-label">
                    Prénom :
                </label>
                <input type="text" class="form-control"
                    id="LastName" placeholder="Nom"
                    value="@Model?.LastName" asp-for="LastName" />
            </div>

            <div>
                <label for="BirthDate" class="control-label">
                    Date de naissance :
                </label>
                <input type="date" class="form-control"
                    id="BirthDate" 
                    value="@Model?.BirthDate?.ToString("yyyy-MM-dd")" 
                    asp-for="BirthDate" />
            </div>

            <div>
                <label for="CityId">
                    Ville : 
                </label>
                @Html.DropDownListFor(
                    // Champ du modèle (quelle ville faut-il sélectionner)
                    // Le moteur Razor sait que p est une Personne
                    // grace à @model Person
                    p => p.CityId,
                    // Remplissage de la liste
                    new SelectList(
                        // Liste des entités qui peuplent la liste
                        // voir @using et @inject en haut de fichier
                        _cityRepository.GetAll(), 
                        // Champ de clé
                        "Id", 
                        // Champ d'affichage
                        "Name"),
                    // Item par défaut
                    "<Sélectionnez une ville>",
                    // Classe CSS
                    // Le @ n'est pas celui de Razor mais celui du C#
                    // Si on veut nommer une classe ou un champ avec un 
                    // mot clé du langage, on le fait précéder d'un @
                    new { @clafss = "form-control" })
            </div>


            <br />

            <input type="submit" class="btn btn-primary"
                value="Valider" />
            <a class="btn btn-default" 
                asp-controller="Person" asp-action="Index">Annuler</a>
        </form>
    </div>
</div>

Isen.DotNet.Web/Views/Person/Index.cshtml
@using Isen.DotNet.Library.Models.Implementation;
@{
    ViewData["Title"] = "Personnes";
}
@model IEnumerable<Person>

<div class="row">
    <div class="col-md-12">
        <h1>Personnes <small>/person/index</small></h1>
    </div>
</div>
<div class="row">
    <a class="btn btn-default" 
        asp-controller="Person" asp-action="Detail">Ajouter une personne...</a>
</div>
<div class="row">
    <table class="table table-striped">
        <thead>
            <tr>
                <th>#</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Nom complet</th>
                <th>Naissance</th>
                <th>Age</th>
                <th>Ville</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach(var person in Model)
            {
            <tr>
                <td>@person.Id</td>
                <td>@person.LastName</td>
                <td>@person.FirstName</td>
                <td>@person.Name</td>
                <td>@person.BirthDate?.ToString("dddd dd MMMM yyyy")</td>
                <td>@person.Age</td>
                <td>@person.City?.Name</td>
                <td>
                    <a class="btn btn-default" 
                        asp-controller="Person" 
                        asp-action="Detail" 
                        asp-route-id="@person.Id">Editer</a>
                    &nbsp;
                    <a class="btn btn-danger" 
                        asp-controller="Person" 
                        asp-action="Delete" 
                        asp-route-id="@person.Id">Supprimer</a>
                </td>
            </tr>
            }
        </tbody>
    </table>
</div>

Isen.DotNet.Web/Views/Shared/_Footer.cshtml
<hr />
<footer>
    <p>&copy; 2018 - Yncrea</p>
</footer>

Isen.DotNet.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | @ViewData["Desc"] - myWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @Html.Partial("_Nav")
    <div class="container body-content">
        <!-- ViewStart est injecté ici -->
        @RenderBody()
        @Html.Partial("_Footer")
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Isen.DotNet.Web/Views/Shared/_LayoutEmpty.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | @ViewData["Desc"] - myWebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        <!-- ViewStart est injecté ici -->
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Isen.DotNet.Web/Views/Shared/_Nav.cshtml
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">my<strong>Web</strong>App</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                <li class="dropdown">
                    <a href="#" 
                        class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false">
                        Communes
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Commune" asp-action="Index">Toutes...</a></li>
                        <li><a asp-controller="Commune" asp-action="Detail">Ajouter...</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" 
                        class="dropdown-toggle"
                        data-toggle="dropdown"
                        role="button"
                        aria-haspopup="true"
                        aria-expanded="false">
                        Adresses
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a asp-controller="Address" asp-action="Index">Toutes...</a></li>
                        <li><a asp-controller="Address" asp-action="Detail">Ajouter...</a></li>
                    </ul>
                </li>
                <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>